### PR TITLE
feat: Detail Page alert description variable text sizing

### PR DESCRIPTION
**Pull request by cmaddox5**
**Asana task**: [[Elevator Detail page] Use variable text sizes for the alert description](https://app.asana.com/0/0/1201901724848538/f)

This is a proposed general solution to variable text sizing for our v2 apps. Took the existing logic and put it in a custom hook. Definitely open to feedback on whether this is the solution we want going forward.

- [ ] Needs version bump?

### CODE REVIEW

**Review by jzimbel-mbta — COMMENTED** [review]
Overall looks great to me, very straightforward.

**Review by PaulJKim — COMMENTED** [review]
Looks good to me as well!

**Review by hannahpurcell — COMMENTED** [review]
I'm excited for this!

Noticed that the sizing does not kick in on initial render, which leads to mis-sized font until the first page turn. I think that's fine. It's only confusing/cumbersome from a developer's perspective (the dev has to wait to see whether the styling is correct.) If there's any way to avoid that, great. If not, the solution is still worth it.

**Comment by cmaddox5** [comment]
> I'm excited for this!
> 
> Noticed that the sizing does not kick in on initial render, which leads to mis-sized font until the first page turn. I think that's fine. It's only confusing/cumbersome from a developer's perspective (the dev has to wait to see whether the styling is correct.) If there's any way to avoid that, great. If not, the solution is still worth it.

@hannahpurcell Weird, I don't seem to be able to reproduce that issue. Can you remake the alert you were testing with and I'll check it out?

**Comment by hannahpurcell** [comment]
> Weird, I don't seem to be able to reproduce that issue. Can you remake the alert you were testing with and I'll check it out?

Just using the current prod alerts, set to Haymarket. Issue only happens if the detail view is the first page that renders. Also, on refresh, I didn't see it appear again... so not totally sure why this is happening. Maybe it's pretty infrequent.

Screen Shot 2022-03-30 at 5 05 18 PM

**Review by hannahpurcell — APPROVED** [review]
The first-render thing will be less of a dev concern than I thought, and it won't impact riders at all. Looks good!

**Pull request merged**
