### PR TITLE
tweak: Add clock icon to Shuttle Bus widget

### PR DESCRIPTION
**Pull request by cmaddox5**
**Asana task**: ad-hoc

Adds the clock icon to the widget. Also fixes some console errors when rendering the new SVGs.

- [ ] Tests added?

### CODE REVIEW

**Review by hannahpurcell — DISMISSED** [review]
This seems to have reverted the config update to using `minutes_range_to_destination_schedule` instead of `minutes_range_to_destination`

**Comment by cmaddox5** [comment]
> This seems to have reverted the config update to using `minutes_range_to_destination_schedule` instead of `minutes_range_to_destination`

The schedule is resolved in the backend, so the front end only receives a single `minutes_range_to_destination`.

**Comment by hannahpurcell** [comment]
> The schedule is resolved in the backend, so the front end only receives a single `minutes_range_to_destination`.

Got it, thanks

**Review by hannahpurcell — COMMENTED** [review]
Can I lift my "requested changes" by just leaving a comment? (answer: no)

**Review by jzimbel-mbta — APPROVED** [review]

**Pull request merged**
